# Site Settings
title: HTML
email: carlossg00@hotmail.com
description: >
  Página del coro A Viva Veu
baseurl: ""
url: "http://a-viva-veu.github.io"
#twitter_username: taniarascia
#github_username:  taniarascia
# Build Settings
sass:
  sass_dir: _sass

collections:
  pages:
    output: true
    permalink: /:path/

permalink: pretty

include: ['_pages','_pages/concerts']

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: "assets/audios"
    values:
      audios: true

kramdown:
  input: GFM
